services:
  app:
    build: .
    image: fooocus
    restart: always
    ports:
      - "7865:7865"
    environment:
      - CMDARGS=--listen # Arguments for launch.py.
      - DATADIR=/app/data # Directory which stores models, outputs dir
      - config_path=/app/data/config.txt
      - config_example_path=/app/data/config_modification_tutorial.txt
      - path_checkpoints=/app/models/checkpoints/
      - path_loras=/app/models/loras/
      - path_embeddings=/app/models/embeddings/
      - path_vae_approx=/app/models/vae_approx/
      - path_upscale_models=/app/models/upscale_models/
      - path_inpaint=/app/models/inpaint/
      - path_controlnet=/app/models/controlnet/
      - path_clip_vision=/app/models/clip_vision/
      - path_fooocus_expansion=/app/models/prompt_expansion/fooocus_expansion/
      - path_outputs=/app/outputs/ # Warning: If it is not located under '/app', you can't see history log!
      - default_advanced_checkbox=True
      - default_save_metadata_to_images=True
    volumes:
      - ./data:/app/data
      - ../models:/app/models # Once you import files, you don't need to mount again.
      - ./outputs:/app/outputs
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [compute, utility, gpu]
